name: Sync Template to Child

on:
  push:
    branches:
      - main

jobs:
  sync:
    if: github.repository == 'crestbharatphalak/temp-repository-test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repo
        uses: actions/checkout@v3

      - name: Sync with child repo and handle conflicts
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: crestbharatphalak/temp-repository-template-v1
          TEMPLATE_REPO: crestbharatphalak/temp-repository-test
        
        run: |
          git config --global user.email "bharat.p@crestinfosystems.com"
          git config --global user.name "Sync-Bot"

          git clone https://x-access-token:${GH_PAT}@github.com/$REPO.git child-repo
          cd child-repo

          git remote add template https://github.com/$TEMPLATE_REPO.git
          git fetch template

          BRANCH_NAME=template-sync-$(date +%d-%m-%Y-%H-%M)
          git checkout -b $BRANCH_NAME

          set +e
          git pull template main --allow-unrelated-histories --no-rebase
          MERGE_EXIT_CODE=$?
          set -e

          if [ "$MERGE_EXIT_CODE" -ne 0 ]; then
            echo "Conflicts Got -> Creating PR for Manual Check..."

            git add .
            git commit -m "Conflict merge from template - manual resolution needed" || true

            git push origin $BRANCH_NAME

            curl -X POST -H "Authorization: token ${GH_PAT}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO/pulls \
              -d '{
                "title": "Merge from template - manual conflict resolution needed ($(date +%d-%m-%Y-%H-%M))",
                "head": "'"$BRANCH_NAME"'",
                "base": "main",
                "body": "Merge conflicts need to be resolved manually in this PR. Please do not merge until resolved."
              }'

          else
            echo "No conflicts, merge successful"

            git push origin $BRANCH_NAME
            git checkout main
            git merge $BRANCH_NAME
            git push origin main

          fi

      # - name: Sync with child repo
      #   run: |
      #     git config --global user.email "bharat.p@crestinfosystems.com"
      #     git config --global user.name "Sync-Bot"
          
      #     git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/crestbharatphalak/temp-repository-template-v1.git child-repo
      #     cd child-repo

      #     git remote add template https://github.com/crestbharatphalak/temp-repository-test.git
      #     git pull template main --allow-unrelated-histories --no-rebase

      #     git push origin main
      #   env:
      #     GIT_ASKPASS: echo
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}
